/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleSumaryCard: typeof import('./src/components/ArticleSumaryCard.vue')['default']
    BlogSumaryCard: typeof import('./src/components/BlogSumaryCard.vue')['default']
    ExperimentTest: typeof import('./src/components/experimentTest.vue')['default']
    InformationTable: typeof import('./src/components/InformationTable.vue')['default']
    MdArticleCatalog: typeof import('./src/components/MdArticleCatalog.vue')['default']
    MdArticlePreview: typeof import('./src/components/MdArticlePreview.vue')['default']
    MdBlogEditor: typeof import('./src/components/MdBlogEditor.vue')['default']
    MdComment: typeof import('./src/components/MdComment.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UComment: typeof import('undraw-ui')['UComment']
    UploadImgComponent: typeof import('./src/components/UploadImgComponent.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
  }
}
