server:
  port: 8080
sa-token:
  token-name: satoken
  is-log: true
spring:
  application:
    name: blogbackend
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.84.207.40:3306/blog_db?serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: 2775313450
  redis:
    host: localhost
    port: 6379
    #    password: 123456
    database: 1 # 数据库索引，默认0
    timeout: 5000  # 连接超时，单位ms

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
      id-type: auto

